~ Added check for minimal version of Packer binary to packer-jsmin script

diff --git a/packer-jsmin b/packer-jsmin
--- a/packer-jsmin
+++ b/packer-jsmin
@@ -1,5 +1,15 @@
 #!/bin/bash
 
+function version_ge() { test "$(printf '%s\n' "$@" | sort -rV | head -n 1)" == "$1"; }
+
+PACKER_BINARY_VERSION=$(packer version | awk '{print $NF}')
+PACKER_BINARY_MIN_VERSION="v1.1.0"
+
+if ! version_ge ${PACKER_BINARY_VERSION} ${PACKER_BINARY_MIN_VERSION}; then
+  echo "ERROR: Packer version '${PACKER_BINARY_MIN_VERSION}' needed, please update your Packer binary (your current version is '${PACKER_BINARY_VERSION}'). Exiting."
+  exit 1
+fi
+
 # Set VM image version to "1.0.0-UNSTABLE" if not specified
 export PACKER_VERSION="${PACKER_VERSION:-1.0.0-UNSTABLE}"
 
